### PR TITLE
System default dark mode

### LINKED ISSUE #35: Add support for dark and light theme
### Description

Implement the support to the light and dark theme in the editor according to the user system settings

### Motivation

Follow the user preferences to show the right editor's theme

### Proposed Implementation

The goal:
- follow the browser settings by default
- implement an attribute in the component to override this behaviour and force a specific theme

### Definition of Done

- [ ] Implementation: Fully implemented according to the Serverless Workflow spec.
- [x] Unit Tests: Comprehensive unit tests are included and passing.
- [ ] Integration Tests: Verified within the monorepo and target environments (Web/VS Code).
- [ ] Documentation: Updated README.md, ADRs, or official docs.
- [ ] Performance: No significant regression in editor responsiveness.
- [x] Accessibility: UI changes comply with accessibility standards.

### PR DESCRIPTION
**Pull request by kumaradityaraj**
Closes [Add support for dark and light theme](https://github.com/serverlessworkflow/editor/issues/35)

This feature implements dark mode by using system current status.

https://github.com/user-attachments/assets/440ef877-f17e-4055-a610-c92a6979db30

### CODE REVIEW

**Comment by lornakelly** [comment]
@kumaradityaraj Thanks for the PR. Looks like this only handles the first part of ticket for system default but the second part needs to be done "implement an attribute in the component to override this behaviour and force a specific theme"

File: packages/serverless-workflow-diagram-editor/src/react-flow/diagram/Diagram.tsx [hunk 1]
```diff
@@ -54,6 +54,7 @@ export const Diagram = ({ divRef, ref }: DiagramProps) => {
   const [minimapVisible, setMinimapVisible] = React.useState(false);
   const [nodes, setNodes] = React.useState<RF.Node[]>(initialNodes);
   const [edges, setEdges] = React.useState<RF.Edge[]>(initialEdges);
+  const [colorMode] = React.useState<RF.ColorMode>("system");
```
Comment (lornakelly) [inline packages/serverless-workflow-diagram-editor/src/react-flow/diagram/Diagram.tsx]: You have no set method here so `useState` isn't what you would use. Based on the second criteria in ticket you want to be able to override so better to have a prop users can use to override and the default value is system

Comment (lornakelly) [reply packages/serverless-workflow-diagram-editor/src/react-flow/diagram/Diagram.tsx]: Please also add tests once implemented, thanks

**Comment by kumaradityaraj** [comment]
@fantonangeli `implement an attribute in the component to override this behaviour and force a specific theme`  by this you mean adding a side button for selecting modes or is it something copilot is suggesting [here](https://github.com/serverlessworkflow/editor/pull/92#discussion_r3086676829)

File: packages/serverless-workflow-diagram-editor/src/react-flow/diagram/Diagram.tsx [hunk 2]
```diff
@@ -89,7 +93,15 @@ export const Diagram = ({ divRef, ref }: DiagramProps) => {
         preventScrolling={true}
         selectionOnDrag={true}
         fitView
+        colorMode={colorMode}
       >
+        <RF.Panel position="top-right">
```
Comment (fantonangeli) [inline packages/serverless-workflow-diagram-editor/src/react-flow/diagram/Diagram.tsx]: We don't need a dropdown as we already have this button in Storybook to change the background
Image

File: packages/serverless-workflow-diagram-editor/test-results/.last-run.json
Comment (fantonangeli) [inline packages/serverless-workflow-diagram-editor/test-results/.last-run.json:1]: leftover?

**Comment by fantonangeli** [comment]
@kumaradityaraj I was thinking about:
- adding a property here:
packages/serverless-workflow-diagram-editor/src/diagram-editor/DiagramEditor.tsx:29
- received from:
packages/serverless-workflow-diagram-editor/stories/DiagramEditor.tsx:26
- and finally passing it to Reactflow like you already did here:
packages/serverless-workflow-diagram-editor/src/react-flow/diagram/Diagram.tsx:96

**Review by fantonangeli — CHANGES_REQUESTED** [review]

File: packages/serverless-workflow-diagram-editor/src/react-flow/diagram/Diagram.css [hunk 3]
```diff
@@ -23,3 +23,10 @@
     --xy-background-pattern-color: #ccc;
     background-color: #E5E4E2;
 }
+
+@media (prefers-color-scheme: dark) {
+    .diagram-background{ 
+        --xy-background-pattern-color: inherit;
+        background-color: inherit;
+    }
+}
```
[the remark this answers is not in the document]
Comment (kumaradityaraj) [reply packages/serverless-workflow-diagram-editor/src/react-flow/diagram/Diagram.css:37]: @fantonangeli  I think it is true to some extent because with the current implementation this feature is breaking if we are playng with the attribute of storybook. Can you suggest something here?

File: packages/serverless-workflow-diagram-editor/src/diagram-editor/DiagramEditor.css [hunk 4]
```diff
@@ -0,0 +1,34 @@
...
+  margin: 0;
+  padding: 1%;
+}
+
+.headingContent.colorMode-dark {
+    color: #F8F8F8;
+    background-color: #141414;
+}
+
+@media (prefers-color-scheme: dark) {
```
Comment (lornakelly) [inline packages/serverless-workflow-diagram-editor/src/diagram-editor/DiagramEditor.css:30]: More of an FYI but because we will be introducing tailwind in a later PR we will need to replace this to tailwind style. I will change this when I am merging tailwind work. For your own info, worth looking up how tailwind implements dark and light styles - no need to change this PR though

File: packages/serverless-workflow-diagram-editor/tests/diagram-editor/DiagramEditor.story.test.tsx [hunk 5]
```diff
@@ -28,10 +28,10 @@ describe("Story - DiagramEditor component", () => {
     vi.restoreAllMocks();
   });
 
-  test("Renders react flow Diagram component", async () => {
-    const locale = "en";
-    const isReadOnly = true;
+  const locale = "en";
+  const isReadOnly = true;
 
+  test("Renders react flow Diagram component", () => {
```
Comment (lornakelly) [inline packages/serverless-workflow-diagram-editor/tests/diagram-editor/DiagramEditor.story.test.tsx]: the pattern we are using for tests is `it` not `test` if you can change for consistency

File: packages/serverless-workflow-diagram-editor/src/diagram-editor/DiagramEditor.css [hunk 6]
```diff
@@ -0,0 +1,35 @@
...
+    .headingContent.colorMode-system {
+        color: #F8F8F8;
+        background-color: #141414;
+    }
+}
```
[the remark this answers is not in the document]
Comment (kumaradityaraj) [reply packages/serverless-workflow-diagram-editor/src/diagram-editor/DiagramEditor.css:35]: this gets updated by tailwind update

**Comment by kumaradityaraj** [comment]
@fantonangeli @lornakelly Its ready for final review.

File: packages/serverless-workflow-diagram-editor/tests/diagram-editor/DiagramEditor.test.tsx [hunk 7]
```diff
@@ -36,4 +36,55 @@ describe("DiagramEditor Component", () => {
 
     expect(reactFlowContainer).toBeInTheDocument();
   });
+
+  test("applies light mode class", () => {
```
Comment (lornakelly) [inline packages/serverless-workflow-diagram-editor/tests/diagram-editor/DiagramEditor.test.tsx]: Need to be changed to `it`

**Review by lornakelly — APPROVED** [review]
LGTM

**Review by fantonangeli — APPROVED** [review]
LGTM, thanks @kumaradityaraj

**Comment by kumaradityaraj** [comment]
@ricardozanini Please review and merge this PR. Thank you.
